Fixes follow reset bug #220
domoritz/leaflet-locatecontrol pull request #221
Opened 2018-11-08 13:45 UTC by brendanheywood

2018-11-08 16:36 UTC, domoritz requested changes

2018-11-08 16:36 UTC, domoritz commented on src/L.Control.Locate.js
> +                    this._ignoreEvent = true;
Please add a comment about why this is necessary.

2018-11-09 00:44 UTC, brendanheywood commented
Hmm this fix isn't good enough, depending on the timing of the requestAnimationFrame the subsequent zoom and zoom event could be async in the next tick which explains why this was intermittent.

2018-11-09 01:16 UTC, brendanheywood commented
Ok this should be pretty solid now. In my research I also found another concept:

https://stackoverflow.com/questions/31992278/detect-user-initiated-pan-zoom-operations-on-leaflet

But that e.hard attribute was never documented and has since been removed from leaflet core

2018-11-09 01:49 UTC, domoritz commented
Thank you!

2018-11-09 01:49 UTC, merged