UPDATE: handled the customization of link text
domoritz/leaflet-locatecontrol pull request #279
Opened 2020-12-23 10:18 UTC by SobhanAminnejad

UPDATE: added buttonText sample in script.js

UPDATE: updated styling of locate me button

UPDATE: added buttonText in the documentation examples

UPDATE: removed buttonText sample in script.js

2020-12-23 15:13 UTC, domoritz requested changes
Thank you for the pull request.

2020-12-23 15:13 UTC, domoritz commented on src/L.Control.Locate.scss
> +    min-height: 30px !important;
Can you try to not require the `!important` annotation? It usually leads to problems in other places.

2020-12-23 15:13 UTC, domoritz commented on src/L.Control.Locate.js
> +                if(options.strings.buttonText) {
Please make the formatting consistent with the rest of the code.

2021-06-23 10:42 UTC, Lunok commented
Hello, I would like if this request is accepted, Any new about it?

2021-06-23 16:59 UTC, domoritz commented
I am waiting for updates to my comments. Please make a new pull request with the changes @Lunok.

2021-06-23 16:59 UTC, closed without merging